### ISSUE TITLE
Error with "delegator_address" field while using genesis_theta.py

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-genesis-tinkerer#2]
When I use a genesis generated using the genesis_theta.py I'm getting this error. I'll continue to investigate
```
eb 13 18:43:22 hydrogen cosmovisor[347907]: panic: unknown field "delegator_address" in types.Validator
Feb 13 18:43:22 hydrogen cosmovisor[347907]: goroutine 1 [running]:
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc00055afc0, 0xc017f80000, 0x1ba0a23, 0x1ba2000, 0x215abf0, 0xc00009b1e0)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/codec/proto_codec.go:160 +0x98
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis(0x2182ef8, 0xc00055afc0, 0x214ce68, 0xc001142530, 0x217d718, 0xc00055afc0, 0x216b3e0, 0xc0002c2240, 0x7f929c241f80, 0xc000545ce0, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/x/staking/module.go:148 +0xa4
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000558cb0, 0x2167848, 0xc000122010, 0x217d128, 0xc000d5f780, 0x0, 0x0, 0xc0002dc460, 0x1d, 0x706ec3, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/types/module/module.go:304 +0x2b5
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/gaia/v5/app.(*GaiaApp).InitChainer(0xc000566800, 0x2167848, 0xc000122010, 0x217d128, 0xc000d5f780, 0x0, 0x0, 0xc0002dc460, 0x1d, 0x706ec3, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/gaia/v5/app/app.go:490 +0x170
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00054ba00, 0x0, 0xed5830c36, 0x0, 0xc0002dc460, 0x1d, 0xc00004adc0, 0xc000560c00, 0x7d, 0x7d, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:62 +0x315
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0002a1740, 0x0, 0xed5830c36, 0x0, 0xc0002dc460, 0x1d, 0xc00004adc0, 0xc000560c00, 0x7d, 0x7d, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:266 +0x115
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0003fa270, 0x0, 0xed5830c36, 0x0, 0xc0002dc460, 0x1d, 0xc00004adc0, 0xc000560c00, 0x7d, 0x7d, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:77 +0x78
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000d12248, 0xb, 0x0, 0x2103278, 0x8, 0xc0002dc460, 0x1d, 0x706ec3, 0x0, 0x0, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:319 +0x655
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d12248, 0x2181388, 0xc0000a8000, 0x1f4, 0xc001142160)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x458
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/tendermint/tendermint/node.doHandshake(0x217d2c8, 0xc0001e8d00, 0xb, 0x0, 0x2103278, 0x8, 0xc0002dc460, 0x1d, 0x706ec3, 0x0, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/tendermint/tendermint/node.NewNode(0xc000e98c80, 0x215f5a0, 0xc0002bef00, 0xc001143ba0, 0x212d040, 0xc000137908, 0xc001143c10, 0x1f414b0, 0xc001143d00, 0x2168450, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x20e5
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000ed3400, 0x0, 0x0, 0x0, 0x21889d8, 0xc000f65b30, 0x0, 0x0, 0x2170a50, 0xc000e7c7d0, ...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:244 +0x585
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000ec8a00, 0xc000f64ab0, 0x0, 0x3, 0x0, 0x0)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:120 +0x209
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/spf13/cobra.(*Command).execute(0xc000ec8a00, 0xc000f64a50, 0x3, 0x3, 0xc000ec8a00, 0xc000f64a50)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000da5680, 0x0, 0x0, 0xc000e7a760)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/spf13/cobra@v1.1.3/command.go:897
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/spf13/cobra@v1.1.3/command.go:890
Feb 13 18:43:22 hydrogen cosmovisor[347907]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000da5680, 0xc000e7a760, 0x10, 0x2182ef8, 0xc000e7c7d0)
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/cosmos-sdk@v0.42.9/server/cmd/execute.go:36 +0x265
Feb 13 18:43:22 hydrogen cosmovisor[347907]: main.main()
Feb 13 18:43:22 hydrogen cosmovisor[347907]:         github.com/cosmos/gaia/v5/cmd/gaiad/main.go:16 +0x45
```

**Comment by uditvira** [comment]
Closing. This was a simple version issue with gaiad. I didn't realize the default in the ansibles was gaiad v5 instead of v6
